package com.strhodler.utxopocket.presentation.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import com.strhodler.utxopocket.domain.model.ThemeProfile

private data class ThemePalette(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val inversePrimary: Color,
    val surfaceDim: Color,
    val surfaceBright: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val surfaceTint: Color = Color.Unspecified,
    val primaryFixed: Color = Color.Unspecified,
    val primaryFixedDim: Color = Color.Unspecified,
    val onPrimaryFixed: Color = Color.Unspecified,
    val onPrimaryFixedVariant: Color = Color.Unspecified,
    val secondaryFixed: Color = Color.Unspecified,
    val secondaryFixedDim: Color = Color.Unspecified,
    val onSecondaryFixed: Color = Color.Unspecified,
    val onSecondaryFixedVariant: Color = Color.Unspecified,
    val tertiaryFixed: Color = Color.Unspecified,
    val tertiaryFixedDim: Color = Color.Unspecified,
    val onTertiaryFixed: Color = Color.Unspecified,
    val onTertiaryFixedVariant: Color = Color.Unspecified
)

private fun ThemePalette.toColorScheme(isDark: Boolean): ColorScheme {
    return if (isDark) {
        darkColorScheme(
            primary = primary,
            onPrimary = onPrimary,
            primaryContainer = primaryContainer,
            onPrimaryContainer = onPrimaryContainer,
            secondary = secondary,
            onSecondary = onSecondary,
            secondaryContainer = secondaryContainer,
            onSecondaryContainer = onSecondaryContainer,
            tertiary = tertiary,
            onTertiary = onTertiary,
            tertiaryContainer = tertiaryContainer,
            onTertiaryContainer = onTertiaryContainer,
            error = error,
            onError = onError,
            errorContainer = errorContainer,
            onErrorContainer = onErrorContainer,
            background = background,
            onBackground = onBackground,
            surface = surface,
            onSurface = onSurface,
            surfaceVariant = surfaceVariant,
            onSurfaceVariant = onSurfaceVariant,
            outline = outline,
            outlineVariant = outlineVariant,
            scrim = scrim,
            inverseSurface = inverseSurface,
            inverseOnSurface = inverseOnSurface,
            inversePrimary = inversePrimary,
            surfaceDim = surfaceDim,
            surfaceBright = surfaceBright,
            surfaceContainerLowest = surfaceContainerLowest,
            surfaceContainerLow = surfaceContainerLow,
            surfaceContainer = surfaceContainer,
            surfaceContainerHigh = surfaceContainerHigh,
            surfaceContainerHighest = surfaceContainerHighest,
            surfaceTint = surfaceTint.takeOrElse { primary },
            primaryFixed = primaryFixed.takeOrElse { primary },
            primaryFixedDim = primaryFixedDim.takeOrElse { primaryContainer },
            onPrimaryFixed = onPrimaryFixed.takeOrElse { onPrimary },
            onPrimaryFixedVariant = onPrimaryFixedVariant.takeOrElse { onPrimaryContainer },
            secondaryFixed = secondaryFixed.takeOrElse { secondary },
            secondaryFixedDim = secondaryFixedDim.takeOrElse { secondaryContainer },
            onSecondaryFixed = onSecondaryFixed.takeOrElse { onSecondary },
            onSecondaryFixedVariant = onSecondaryFixedVariant.takeOrElse { onSecondaryContainer },
            tertiaryFixed = tertiaryFixed.takeOrElse { tertiary },
            tertiaryFixedDim = tertiaryFixedDim.takeOrElse { tertiaryContainer },
            onTertiaryFixed = onTertiaryFixed.takeOrElse { onTertiary },
            onTertiaryFixedVariant = onTertiaryFixedVariant.takeOrElse { onTertiaryContainer }
        )
    } else {
        lightColorScheme(
            primary = primary,
            onPrimary = onPrimary,
            primaryContainer = primaryContainer,
            onPrimaryContainer = onPrimaryContainer,
            secondary = secondary,
            onSecondary = onSecondary,
            secondaryContainer = secondaryContainer,
            onSecondaryContainer = onSecondaryContainer,
            tertiary = tertiary,
            onTertiary = onTertiary,
            tertiaryContainer = tertiaryContainer,
            onTertiaryContainer = onTertiaryContainer,
            error = error,
            onError = onError,
            errorContainer = errorContainer,
            onErrorContainer = onErrorContainer,
            background = background,
            onBackground = onBackground,
            surface = surface,
            onSurface = onSurface,
            surfaceVariant = surfaceVariant,
            onSurfaceVariant = onSurfaceVariant,
            outline = outline,
            outlineVariant = outlineVariant,
            scrim = scrim,
            inverseSurface = inverseSurface,
            inverseOnSurface = inverseOnSurface,
            inversePrimary = inversePrimary,
            surfaceDim = surfaceDim,
            surfaceBright = surfaceBright,
            surfaceContainerLowest = surfaceContainerLowest,
            surfaceContainerLow = surfaceContainerLow,
            surfaceContainer = surfaceContainer,
            surfaceContainerHigh = surfaceContainerHigh,
            surfaceContainerHighest = surfaceContainerHighest,
            surfaceTint = surfaceTint.takeOrElse { primary },
            primaryFixed = primaryFixed.takeOrElse { primary },
            primaryFixedDim = primaryFixedDim.takeOrElse { primaryContainer },
            onPrimaryFixed = onPrimaryFixed.takeOrElse { onPrimary },
            onPrimaryFixedVariant = onPrimaryFixedVariant.takeOrElse { onPrimaryContainer },
            secondaryFixed = secondaryFixed.takeOrElse { secondary },
            secondaryFixedDim = secondaryFixedDim.takeOrElse { secondaryContainer },
            onSecondaryFixed = onSecondaryFixed.takeOrElse { onSecondary },
            onSecondaryFixedVariant = onSecondaryFixedVariant.takeOrElse { onSecondaryContainer },
            tertiaryFixed = tertiaryFixed.takeOrElse { tertiary },
            tertiaryFixedDim = tertiaryFixedDim.takeOrElse { tertiaryContainer },
            onTertiaryFixed = onTertiaryFixed.takeOrElse { onTertiary },
            onTertiaryFixedVariant = onTertiaryFixedVariant.takeOrElse { onTertiaryContainer }
        )
    }
}

private fun Color.takeOrElse(fallback: () -> Color): Color =
    if (this == Color.Unspecified) fallback() else this

private val brandLightPalette = ThemePalette(
    primary = Color(0xFFF7931A),
    onPrimary = Color(0xFF000000),
    primaryContainer = Color(0xFFD97706),
    onPrimaryContainer = Color(0xFF000000),
    secondary = Color(0xFF2E2E2E),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE5E7EB),
    onSecondaryContainer = Color(0xFF111827),
    tertiary = Color(0xFF00664F),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD1FAE5),
    onTertiaryContainer = Color(0xFF1F2937),
    error = Color(0xFFDC2626),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFEE2E2),
    onErrorContainer = Color(0xFF7F1D1D),
    background = Color(0xFFF9FAFB),
    onBackground = Color(0xFF1F2937),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF111827),
    surfaceVariant = Color(0xFFF3F4F6),
    onSurfaceVariant = Color(0xFF4B5563),
    outline = Color(0xFF9CA3AF),
    outlineVariant = Color(0xFFE5E7EB),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF1F2937),
    inverseOnSurface = Color(0xFFF9FAFB),
    inversePrimary = Color(0xFFF7931A),
    surfaceDim = Color(0xFFE5E7EB),
    surfaceBright = Color(0xFFFFFFFF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF3F4F6),
    surfaceContainer = Color(0xFFE5E7EB),
    surfaceContainerHigh = Color(0xFFD1D5DB),
    surfaceContainerHighest = Color(0xFF9CA3AF),
    surfaceTint = Color(0xFFF7931A),
    primaryFixed = Color(0xFFF7931A),
    primaryFixedDim = Color(0xFFD97706),
    onPrimaryFixed = Color(0xFF000000),
    onPrimaryFixedVariant = Color(0xFF000000),
    secondaryFixed = Color(0xFF2E2E2E),
    secondaryFixedDim = Color(0xFF4B5563),
    onSecondaryFixed = Color(0xFFFFFFFF),
    onSecondaryFixedVariant = Color(0xFFF9FAFB),
    tertiaryFixed = Color(0xFF00664F),
    tertiaryFixedDim = Color(0xFF1E293B),
    onTertiaryFixed = Color(0xFFFFFFFF),
    onTertiaryFixedVariant = Color(0xFFF1F5F9)
)

private val brandDarkPalette = ThemePalette(
    primary = Color(0xFFF7931A),
    onPrimary = Color(0xFF000000),
    primaryContainer = Color(0xFFD97706),
    onPrimaryContainer = Color(0xFF000000),
    secondary = Color(0xFF374151),
    onSecondary = Color(0xFFE5E7EB),
    secondaryContainer = Color(0xFF4B5563),
    onSecondaryContainer = Color(0xFFF9FAFB),
    tertiary = Color(0xFF00664F),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF1E293B),
    onTertiaryContainer = Color(0xFFF1F5F9),
    error = Color(0xFFF87171),
    onError = Color(0xFF000000),
    errorContainer = Color(0xFF7F1D1D),
    onErrorContainer = Color(0xFFFEE2E2),
    background = Color(0xFF111827),
    onBackground = Color(0xFFF9FAFB),
    surface = Color(0xFF1F2937),
    onSurface = Color(0xFFF3F4F6),
    surfaceVariant = Color(0xFF374151),
    onSurfaceVariant = Color(0xFFE5E7EB),
    outline = Color(0xFF6B7280),
    outlineVariant = Color(0xFF9CA3AF),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFF9FAFB),
    inverseOnSurface = Color(0xFF1F2937),
    inversePrimary = Color(0xFFF7931A),
    surfaceDim = Color(0xFF111827),
    surfaceBright = Color(0xFF334155),
    surfaceContainerLowest = Color(0xFF0F172A),
    surfaceContainerLow = Color(0xFF1E293B),
    surfaceContainer = Color(0xFF273449),
    surfaceContainerHigh = Color(0xFF32455F),
    surfaceContainerHighest = Color(0xFF3F5676),
    surfaceTint = Color(0xFFF7931A),
    primaryFixed = Color(0xFFF7931A),
    primaryFixedDim = Color(0xFFD97706),
    onPrimaryFixed = Color(0xFF000000),
    onPrimaryFixedVariant = Color(0xFF000000),
    secondaryFixed = Color(0xFF4B5563),
    secondaryFixedDim = Color(0xFF374151),
    onSecondaryFixed = Color(0xFFF9FAFB),
    onSecondaryFixedVariant = Color(0xFFE5E7EB),
    tertiaryFixed = Color(0xFF00664F),
    tertiaryFixedDim = Color(0xFF1E293B),
    onTertiaryFixed = Color(0xFFFFFFFF),
    onTertiaryFixedVariant = Color(0xFFF1F5F9)
)

private val deuteranopiaLight = ThemePalette(
    primary = Color(0xFFE07B00),
    onPrimary = Color(0xFF000000),
    primaryContainer = Color(0xFFB88A00),
    onPrimaryContainer = Color(0xFF000000),
    secondary = Color(0xFF4B4B4B),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE5E7EB),
    onSecondaryContainer = Color(0xFF111827),
    tertiary = Color(0xFF005F73),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD1FAE5),
    onTertiaryContainer = Color(0xFF1F2937),
    error = Color(0xFFDC2626),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFEE2E2),
    onErrorContainer = Color(0xFF7F1D1D),
    background = Color(0xFFF9FAFB),
    onBackground = Color(0xFF1F2937),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF111827),
    surfaceVariant = Color(0xFFF3F4F6),
    onSurfaceVariant = Color(0xFF4B5563),
    outline = Color(0xFF9CA3AF),
    outlineVariant = Color(0xFFE5E7EB),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF1F2937),
    inverseOnSurface = Color(0xFFF9FAFB),
    inversePrimary = Color(0xFFE07B00),
    surfaceDim = Color(0xFFE5E7EB),
    surfaceBright = Color(0xFFFFFFFF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF3F4F6),
    surfaceContainer = Color(0xFFE5E7EB),
    surfaceContainerHigh = Color(0xFFD1D5DB),
    surfaceContainerHighest = Color(0xFF9CA3AF),
    surfaceTint = Color(0xFFE07B00),
    primaryFixed = Color(0xFFE07B00),
    primaryFixedDim = Color(0xFFB88A00),
    onPrimaryFixed = Color(0xFF000000),
    onPrimaryFixedVariant = Color(0xFF000000),
    secondaryFixed = Color(0xFF4B4B4B),
    secondaryFixedDim = Color(0xFF4B5563),
    onSecondaryFixed = Color(0xFFFFFFFF),
    onSecondaryFixedVariant = Color(0xFFF9FAFB),
    tertiaryFixed = Color(0xFF005F73),
    tertiaryFixedDim = Color(0xFF1E293B),
    onTertiaryFixed = Color(0xFFFFFFFF),
    onTertiaryFixedVariant = Color(0xFFF1F5F9)
)

private val deuteranopiaDark = ThemePalette(
    primary = Color(0xFFE07B00),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB88A00),
    onPrimaryContainer = Color(0xFF000000),
    secondary = Color(0xFF374151),
    onSecondary = Color(0xFFE5E7EB),
    secondaryContainer = Color(0xFF4B5563),
    onSecondaryContainer = Color(0xFFF9FAFB),
    tertiary = Color(0xFF005F73),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF1E293B),
    onTertiaryContainer = Color(0xFFF1F5F9),
    error = Color(0xFFF87171),
    onError = Color(0xFF000000),
    errorContainer = Color(0xFF7F1D1D),
    onErrorContainer = Color(0xFFFEE2E2),
    background = Color(0xFF111827),
    onBackground = Color(0xFFF9FAFB),
    surface = Color(0xFF1F2937),
    onSurface = Color(0xFFF3F4F6),
    surfaceVariant = Color(0xFF374151),
    onSurfaceVariant = Color(0xFFE5E7EB),
    outline = Color(0xFF6B7280),
    outlineVariant = Color(0xFF9CA3AF),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFF9FAFB),
    inverseOnSurface = Color(0xFF1F2937),
    inversePrimary = Color(0xFFE07B00),
    surfaceDim = Color(0xFF111827),
    surfaceBright = Color(0xFF334155),
    surfaceContainerLowest = Color(0xFF0F172A),
    surfaceContainerLow = Color(0xFF1E293B),
    surfaceContainer = Color(0xFF273449),
    surfaceContainerHigh = Color(0xFF32455F),
    surfaceContainerHighest = Color(0xFF3F5676),
    surfaceTint = Color(0xFFE07B00),
    primaryFixed = Color(0xFFE07B00),
    primaryFixedDim = Color(0xFFB88A00),
    onPrimaryFixed = Color(0xFFFFFFFF),
    onPrimaryFixedVariant = Color(0xFF000000),
    secondaryFixed = Color(0xFF4B5563),
    secondaryFixedDim = Color(0xFF374151),
    onSecondaryFixed = Color(0xFFF9FAFB),
    onSecondaryFixedVariant = Color(0xFFE5E7EB),
    tertiaryFixed = Color(0xFF005F73),
    tertiaryFixedDim = Color(0xFF1E293B),
    onTertiaryFixed = Color(0xFFFFFFFF),
    onTertiaryFixedVariant = Color(0xFFF1F5F9)
)

private val protanopiaLight = ThemePalette(
    primary = Color(0xFFFFAA33),
    onPrimary = Color(0xFF000000),
    primaryContainer = Color(0xFFCC9900),
    onPrimaryContainer = Color(0xFF000000),
    secondary = Color(0xFF5B5B5B),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE5E7EB),
    onSecondaryContainer = Color(0xFF111827),
    tertiary = Color(0xFF00796B),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD1FAE5),
    onTertiaryContainer = Color(0xFF1F2937),
    error = Color(0xFFDC2626),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFEE2E2),
    onErrorContainer = Color(0xFF7F1D1D),
    background = Color(0xFFF9FAFB),
    onBackground = Color(0xFF1F2937),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF111827),
    surfaceVariant = Color(0xFFF3F4F6),
    onSurfaceVariant = Color(0xFF4B5563),
    outline = Color(0xFF9CA3AF),
    outlineVariant = Color(0xFFE5E7EB),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF1F2937),
    inverseOnSurface = Color(0xFFF9FAFB),
    inversePrimary = Color(0xFFFFAA33),
    surfaceDim = Color(0xFFE5E7EB),
    surfaceBright = Color(0xFFFFFFFF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF3F4F6),
    surfaceContainer = Color(0xFFE5E7EB),
    surfaceContainerHigh = Color(0xFFD1D5DB),
    surfaceContainerHighest = Color(0xFF9CA3AF),
    surfaceTint = Color(0xFFFFAA33),
    primaryFixed = Color(0xFFFFAA33),
    primaryFixedDim = Color(0xFFCC9900),
    onPrimaryFixed = Color(0xFF000000),
    onPrimaryFixedVariant = Color(0xFF000000),
    secondaryFixed = Color(0xFF5B5B5B),
    secondaryFixedDim = Color(0xFF4B5563),
    onSecondaryFixed = Color(0xFFFFFFFF),
    onSecondaryFixedVariant = Color(0xFFF9FAFB),
    tertiaryFixed = Color(0xFF00796B),
    tertiaryFixedDim = Color(0xFF1E293B),
    onTertiaryFixed = Color(0xFFFFFFFF),
    onTertiaryFixedVariant = Color(0xFFF1F5F9)
)

private val protanopiaDark = ThemePalette(
    primary = Color(0xFFFFAA33),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFCC9900),
    onPrimaryContainer = Color(0xFF000000),
    secondary = Color(0xFF374151),
    onSecondary = Color(0xFFE5E7EB),
    secondaryContainer = Color(0xFF4B5563),
    onSecondaryContainer = Color(0xFFF9FAFB),
    tertiary = Color(0xFF00796B),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF1E293B),
    onTertiaryContainer = Color(0xFFF1F5F9),
    error = Color(0xFFF87171),
    onError = Color(0xFF000000),
    errorContainer = Color(0xFF7F1D1D),
    onErrorContainer = Color(0xFFFEE2E2),
    background = Color(0xFF111827),
    onBackground = Color(0xFFF9FAFB),
    surface = Color(0xFF1F2937),
    onSurface = Color(0xFFF3F4F6),
    surfaceVariant = Color(0xFF374151),
    onSurfaceVariant = Color(0xFFE5E7EB),
    outline = Color(0xFF6B7280),
    outlineVariant = Color(0xFF9CA3AF),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFF9FAFB),
    inverseOnSurface = Color(0xFF1F2937),
    inversePrimary = Color(0xFFFFAA33),
    surfaceDim = Color(0xFF111827),
    surfaceBright = Color(0xFF334155),
    surfaceContainerLowest = Color(0xFF0F172A),
    surfaceContainerLow = Color(0xFF1E293B),
    surfaceContainer = Color(0xFF273449),
    surfaceContainerHigh = Color(0xFF32455F),
    surfaceContainerHighest = Color(0xFF3F5676),
    surfaceTint = Color(0xFFFFAA33),
    primaryFixed = Color(0xFFFFAA33),
    primaryFixedDim = Color(0xFFCC9900),
    onPrimaryFixed = Color(0xFFFFFFFF),
    onPrimaryFixedVariant = Color(0xFF000000),
    secondaryFixed = Color(0xFF4B5563),
    secondaryFixedDim = Color(0xFF374151),
    onSecondaryFixed = Color(0xFFF9FAFB),
    onSecondaryFixedVariant = Color(0xFFE5E7EB),
    tertiaryFixed = Color(0xFF00796B),
    tertiaryFixedDim = Color(0xFF1E293B),
    onTertiaryFixed = Color(0xFFFFFFFF),
    onTertiaryFixedVariant = Color(0xFFF1F5F9)
)

private val tritanopiaLight = ThemePalette(
    primary = Color(0xFFD97706),
    onPrimary = Color(0xFF000000),
    primaryContainer = Color(0xFFB8860B),
    onPrimaryContainer = Color(0xFF000000),
    secondary = Color(0xFF424242),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE5E7EB),
    onSecondaryContainer = Color(0xFF111827),
    tertiary = Color(0xFF117A65),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFD1FAE5),
    onTertiaryContainer = Color(0xFF1F2937),
    error = Color(0xFFDC2626),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFEE2E2),
    onErrorContainer = Color(0xFF7F1D1D),
    background = Color(0xFFF9FAFB),
    onBackground = Color(0xFF1F2937),
    surface = Color(0xFFFFFFFF),
    onSurface = Color(0xFF111827),
    surfaceVariant = Color(0xFFF3F4F6),
    onSurfaceVariant = Color(0xFF4B5563),
    outline = Color(0xFF9CA3AF),
    outlineVariant = Color(0xFFE5E7EB),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF1F2937),
    inverseOnSurface = Color(0xFFF9FAFB),
    inversePrimary = Color(0xFFD97706),
    surfaceDim = Color(0xFFE5E7EB),
    surfaceBright = Color(0xFFFFFFFF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF3F4F6),
    surfaceContainer = Color(0xFFE5E7EB),
    surfaceContainerHigh = Color(0xFFD1D5DB),
    surfaceContainerHighest = Color(0xFF9CA3AF),
    surfaceTint = Color(0xFFD97706),
    primaryFixed = Color(0xFFD97706),
    primaryFixedDim = Color(0xFFB8860B),
    onPrimaryFixed = Color(0xFF000000),
    onPrimaryFixedVariant = Color(0xFF000000),
    secondaryFixed = Color(0xFF424242),
    secondaryFixedDim = Color(0xFF4B5563),
    onSecondaryFixed = Color(0xFFFFFFFF),
    onSecondaryFixedVariant = Color(0xFFF9FAFB),
    tertiaryFixed = Color(0xFF117A65),
    tertiaryFixedDim = Color(0xFF1E293B),
    onTertiaryFixed = Color(0xFFFFFFFF),
    onTertiaryFixedVariant = Color(0xFFF1F5F9)
)

private val tritanopiaDark = ThemePalette(
    primary = Color(0xFFD97706),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB8860B),
    onPrimaryContainer = Color(0xFF000000),
    secondary = Color(0xFF374151),
    onSecondary = Color(0xFFE5E7EB),
    secondaryContainer = Color(0xFF4B5563),
    onSecondaryContainer = Color(0xFFF9FAFB),
    tertiary = Color(0xFF117A65),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF1E293B),
    onTertiaryContainer = Color(0xFFF1F5F9),
    error = Color(0xFFF87171),
    onError = Color(0xFF000000),
    errorContainer = Color(0xFF7F1D1D),
    onErrorContainer = Color(0xFFFEE2E2),
    background = Color(0xFF111827),
    onBackground = Color(0xFFF9FAFB),
    surface = Color(0xFF1F2937),
    onSurface = Color(0xFFF3F4F6),
    surfaceVariant = Color(0xFF374151),
    onSurfaceVariant = Color(0xFFE5E7EB),
    outline = Color(0xFF6B7280),
    outlineVariant = Color(0xFF9CA3AF),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFF9FAFB),
    inverseOnSurface = Color(0xFF1F2937),
    inversePrimary = Color(0xFFD97706),
    surfaceDim = Color(0xFF111827),
    surfaceBright = Color(0xFF334155),
    surfaceContainerLowest = Color(0xFF0F172A),
    surfaceContainerLow = Color(0xFF1E293B),
    surfaceContainer = Color(0xFF273449),
    surfaceContainerHigh = Color(0xFF32455F),
    surfaceContainerHighest = Color(0xFF3F5676),
    surfaceTint = Color(0xFFD97706),
    primaryFixed = Color(0xFFD97706),
    primaryFixedDim = Color(0xFFB8860B),
    onPrimaryFixed = Color(0xFFFFFFFF),
    onPrimaryFixedVariant = Color(0xFF000000),
    secondaryFixed = Color(0xFF4B5563),
    secondaryFixedDim = Color(0xFF374151),
    onSecondaryFixed = Color(0xFFF9FAFB),
    onSecondaryFixedVariant = Color(0xFFE5E7EB),
    tertiaryFixed = Color(0xFF117A65),
    tertiaryFixedDim = Color(0xFF1E293B),
    onTertiaryFixed = Color(0xFFFFFFFF),
    onTertiaryFixedVariant = Color(0xFFF1F5F9)
)

private val palettesByProfile: Map<ThemeProfile, Pair<ThemePalette, ThemePalette>> = mapOf(
    ThemeProfile.STANDARD to (brandLightPalette to brandDarkPalette),
    ThemeProfile.DEUTERANOPIA to (deuteranopiaLight to deuteranopiaDark),
    ThemeProfile.PROTANOPIA to (protanopiaLight to protanopiaDark),
    ThemeProfile.TRITANOPIA to (tritanopiaLight to tritanopiaDark)
)

fun colorSchemeFor(profile: ThemeProfile, isDark: Boolean): ColorScheme {
    val palettes = palettesByProfile[profile] ?: palettesByProfile.getValue(ThemeProfile.STANDARD)
    val palette = if (isDark) palettes.second else palettes.first
    return palette.toColorScheme(isDark)
}

// Semantic status colors from brand palette (shared across profiles)
val statusSuccess = Color(0xFF22C55E)
val statusWarning = Color(0xFFFACC15)
val statusError = Color(0xFFDC2626)
val statusInfo = Color(0xFF3B82F6)

// Legacy aliases used by previews/settings (standard palette)
val primaryLight = brandLightPalette.primary
val onPrimaryLight = brandLightPalette.onPrimary
val primaryContainerLight = brandLightPalette.primaryContainer
val onPrimaryContainerLight = brandLightPalette.onPrimaryContainer
val secondaryLight = brandLightPalette.secondary
val onSecondaryLight = brandLightPalette.onSecondary
val secondaryContainerLight = brandLightPalette.secondaryContainer
val onSecondaryContainerLight = brandLightPalette.onSecondaryContainer

val primaryDark = brandDarkPalette.primary
val onPrimaryDark = brandDarkPalette.onPrimary
val primaryContainerDark = brandDarkPalette.primaryContainer
val onPrimaryContainerDark = brandDarkPalette.onPrimaryContainer
val secondaryDark = brandDarkPalette.secondary
val onSecondaryDark = brandDarkPalette.onSecondary
val secondaryContainerDark = brandDarkPalette.secondaryContainer
val onSecondaryContainerDark = brandDarkPalette.onSecondaryContainer
